
services:
  - type: web
    name: anime-sama-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    autoDeploy: false
